import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Line from "@/components/Line";

export default function Home() {
  return (
    <>
      <Head>
        <title>Board</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Line />
      </main>
    </>
  );
}
